### ISSUE TITLE
make + make run, does not work on linux

### ISSUE THREAD

**Issue by hhirsch** [brentn/StenoTray#22]
$ make run
java -Djava.ext.dirs=. -Djava.library.path=. StenoTray
Fehler: Hauptklasse StenoTray konnte nicht gefunden oder geladen werden
make: *** [run] Fehler 1

**Comment by brentn** [comment]
You shouldn't have to make it.  Just run the jar file

**Comment by hhirsch** [comment]
That was what failed first so I. Does not find the main class.

**Comment by brentn** [comment]
Then it could be the java version.  I've had other complaints that were
solved by using another version of java.
I use Linux (mint) myself, so I'm sure it works.

**Comment by hhirsch** [comment]
No problem then if it is not designed to run on my machine, I move on. OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-5~deb7u1)
