### ISSUE TITLE
Indicate required Java version is 8

### ISSUE THREAD

**Issue by chajadan** [brentn/StenoTray#23]
I tried running this with 7 and got an esoteric error message. Installing jdk8 helped, after I updated/fixed my path and deleted some old executables (java.exe javaw.exe javaws.exe) from my windows\system32 directory. That's all a lot of work for a non-technical person to get this up and running.

Here are some stackoverflow's that helped me:
http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0
http://stackoverflow.com/questions/15277496/registry-key-has-value-1-7-but-1-6-is-required-java-1-7-is-installed

**Comment by morinted** [comment]
Or build with Java 7.
